# Generated by Django 3.1.4 on 2020-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201211_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
