# Generated by Django 3.1.4 on 2020-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201211_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(default='preview', max_length=200),
            preserve_default=False,
        ),
    ]
